server:
  port: '@server.port@'
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev
service:
  mg:
    automaton:
      url: http://localhost:8080/v1/automaton
      namespace: schedulator
    eventSink:
      url: http://localhost:8022/v1/event_sink
      sinkId: schedulator
    networkTimeout: 5000
  dominant:
    url: http://dominant:8022/v1/domain/repository_client
    networkTimeout: 5000
retry-policy:
  dominant:
    maxAttempts: 10
  job:
    intervalSeconds: 35

cache:
  maxSize: 100
